# Main Compose file, always used.
# Only put things in here that apply to ALL configurations.
#
# Defines portions of the API service, along with the nginx and CDD Tool frontend services.

volumes:
  db-data:

services:
  api:
    image: iamkeldev/opendi-example-api-go:v0.1.0
    build: ./go-model-api
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE:-sqlite}
      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${modelsdb:-}
    volumes:
      - db-data:/db-data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v0/health"]
      start_period: 30s
      start_interval: 10s
      interval: 60s
      timeout: 5s
      retries: 5
  cdd-tool:
    image: iamkeldev/opendi-cdd-authoring-tool:v0.1.0
    build: ./cdd-authoring-tool
    depends_on:
      - api
  
  nginx:
    image: nginx
    volumes:
      - ./nginx-configs:/etc/nginx/configs
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      api:
        condition: service_healthy
      cdd-tool:
        condition: service_started
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if [ "$DATABASE_TYPE" = "sqlite" ]; then
          cp /etc/nginx/configs/nginx-sqlite.conf /etc/nginx/conf.d/default.conf;
        else
          cp /etc/nginx/configs/nginx-db.conf /etc/nginx/conf.d/default.conf;
        fi
        exec nginx -g "daemon off;"