volumes:
  db-data:

services:
  cdd-tool:
    build: ./cdd-authoring-tool
    depends_on:
      - api
  
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - cdd-tool